### ISSUE TITLE
Unable to build -  module path "embed": missing dot in first path element

### ISSUE THREAD

**Issue by bergercookie** [nomad-software/meme#13]
I'm getting the following error when trying to build the project from source:

```
22:58:40 ➜ go build -v
build github.com/nomad-software/meme: cannot load embed: malformed module path "embed": missing dot in first path element
```

Go version: go version go1.13.8 linux/amd64

Is this a bug or am I doing something wrong on my end?

**Comment by nomad-software** [comment]
Since this PR https://github.com/nomad-software/meme/pull/12 this project now requires Go v1.16+

**Comment by bergercookie** [comment]
I see, thanks!
I think it would make sense to also put this in the README.

**Comment by nomad-software** [comment]
Done.
