### ISSUE TITLE
Add option to list the template images

### ISSUE THREAD

**Issue by bergercookie** [nomad-software/meme#14]
I want to add a plugin for running meme and generating a custom meme via the [Albert](https://github.com/albertlauncher/albert) launcher. Something similar to plugins like

* https://github.com/bergercookie/awesome-albert-plugins/blob/master/misc/tldr.gif
* https://github.com/bergercookie/awesome-albert-plugins/blob/master/plugins/image_search/misc/demo0.png

To do so I need to know the template memes already available. I could get them by parsing the help page but that's fragile. Can we add a `--list-templates` CLI option or something similar to get just the list of templates?

**Comment by nomad-software** [comment]
Done.

**Comment by bergercookie** [comment]
Wow, super fast response,
thank you!
