### ISSUE TITLE
Using this tool in Albert meme-generator

### ISSUE THREAD

**Issue by bergercookie** [nomad-software/meme#15]
Hi there,

FYI  I'm using `meme`  under the hood to generate memes using my Albert  plugin.

You can find it [here](https://github.com/bergercookie/awesome-albert-plugins/tree/master/plugins/meme_generator), and here's a demo of it:

![](https://raw.githubusercontent.com/bergercookie/awesome-albert-plugins/master/plugins/meme_generator/misc/demo.gif)

Thanks again for this awesome tool!

**Comment by nomad-software** [comment]
Ha, nice one! :)
