### ISSUE TITLE
CLI Option to write the vanilla images path

### ISSUE THREAD

**Issue by bergercookie** [nomad-software/meme#20]
Hi there @nomad-software,

Could you add a CLI option for outputting the directory in which the vanilla images are stored?
It should be something like `.../packages/pkg/mod/github.com/nomad-software/meme@v1.0.1/data/images`, e.g.,  `--raw-images-path`

I've been using something [like this  trick until now](https://github.com/bergercookie/awesome-albert-plugins/blob/contacts/plugins/meme_generator/__init__.py#L59=) but this doesn't play well with version shims, e.g., when using software like [asdf](https://github.com/asdf-vm/asdf)

**Comment by nomad-software** [comment]
Hi, the images you're referring to are part of this repository. When compiled, the images are embedded within the binary itself.

**Comment by bergercookie** [comment]
I see, thanks

**Comment by Kaligule** [comment]
In my opinion, this would still be a useful feature.

It would allow users to have a template directory with their own images.
They could then `alias meme='meme --template-path=/path/to/meme/templates'.
