### ISSUE TITLE
Show built-in templates

### ISSUE THREAD

**Issue by nii236** [nomad-software/meme#4]
I noticed that the data/images folder has a list of the templates available for use. Unfortunately there is no way to list the various available templates from the CLI app.

I suggest perhaps adding a switch `-l` that will list available templates.

**Comment by nomad-software** [comment]
You can use `meme -h` to list all the templates. I'll make it more obvious in the readme file.

**Comment by nii236** [comment]
Ah cool thanks, I was using `--help` and assumed it was the long form of `-h` I was looking at the help text.

**Comment by nomad-software** [comment]
I've added the long form now too.

**Comment by nomad-software** [comment]
I've also added all the templates to the readme file.
