### ISSUE TITLE
Unhelpful High School Teacher

### ISSUE THREAD

**Issue by guycalledseven** [nomad-software/meme#6]
I think we need this one as well. 

Template:
http://generator-meme.com/inc/media/memes/unhelpful-highschool-teacher.jpg

Thank you for great project! 👍

**Comment by nomad-software** [comment]
He he thanks, I'll get it added over the weekend 😊

⁣
-- 
Regards, 

Gary Wiloughby 
gary@nomad.so ​

**Comment by nomad-software** [comment]
I've updated my meme tool to include another 11 meme templates including 
the unhelpful high school teacher one.

Just do a `go get -u github.com/nomad-software/meme` to update and install.

Have fun! :-)
