### ISSUE TITLE
Add option to select output resolution

### ISSUE THREAD

**Issue by Kagami** [nomad-software/meme#7]
600x600px is quite small in some cases, it would be nice to make it configurable.

**Comment by nomad-software** [comment]
I've taken a look at the size and I think you are right that 600px is a little bit small. Looking at the mean size of all the meme backgrounds the size should be about 650px so I've increased it to this. https://github.com/nomad-software/meme/commit/07e2b058cd96e815341cf5c48fd0221624131962

I don't want to make it configurable as I would also have to make the text size and drawing areas configurable. There is a fine balance when drawing everything to make it look right. Too much space here and there would not make it look like the memes we've all come to love.
